{% set name = "napari-conidie" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-conidie-{{ version }}.tar.gz
  sha256: d9b074d61a6a684a350e4a3e654dc31dc24ae59767cb1a1a34c2a7dbdf262c0e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8,<3.11
  run:
    - h5py
    - magicgui
    - matplotlib-base
    - napari >=0.4.17
    - numpy
    - pandas
    - python >=3.8,<3.11
    - qtpy
    - scikit-image

test:
  imports:
    - napari_conidie
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hereariim/napari-conidie
  summary: A segmentation tool to get conidie and hyphe
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
